name: Post CI Workflow

on:
  workflow_run:
    workflows: ["Dev Continuous Integration Workflow"] # Must match the name of the first workflow
    types:
      - completed   # This triggers when the first workflow is completed

jobs:
  post_ci:
    name: 'Build & Push Image'
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Run post-build tasks'
        run: echo "This runs after the first workflow finishes"
    
      - name: 'Create datestamp image tag'
        run: echo "IMAGE_TAG=$(date +%d-%m-%Y.%H%M)" >> $GITHUB_ENV

      - name: 'Log in to Docker Hub'
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: 'Docker build image'
        run: make image

      - name: 'Push to container registry'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: make push
