name: Cd_ci

# This workflow is triggered whenever a new PR is created on the dev branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

    
jobs:
  # Building the project to make sure everything is ok
  test:
    name: 'Run Frontend and Backend Tests'
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        shell: bash  # Properly indented here
        
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
      
      # Set environment variables
      - name: 'Set up environment variables'
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          cp .env ./backend/.env
      
      # Backend Build
      - name: 'Install Backend Dependencies'
        working-directory: ./backend
        run: npm install 
        
      - name: 'Run Data Migration'
        working-directory: ./backend
        run: npx prisma migrate dev 
        
      - name: 'Build Backend Server'
        working-directory: ./backend
        run: npm run build
        
      # Frontend Build
      - name: 'Install Frontend Dependencies'
        working-directory: ./frontend 
        run: npm install
        
      - name: 'Build Frontend Server'
        working-directory: ./frontend 
        run: npm run build
