name: Cd_build

on:
  workflow_run:
    workflows: ["Cd_ci"] # Must match the name of the first workflow
    types:
      - completed   # This triggers when the first workflow is completed

jobs:
  post_ci:
    name: 'Build & Push Image'
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

         # Set environment variables
      - name: 'Set up environment variables'
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD}}" >> .env 
          echo "DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}" >> .env 
          
          cp .env ./backend/.env

      - name: 'Set up Docker'
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest' 

      - name: 'Install docker-compose'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y docker-compose

      - name: 'Run post-build tasks'
        run: echo "This runs after the first workflow finishes"
    
      - name: 'Log in to Docker Hub'
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: 'Docker build image'
        run: make image

      - name: 'Docker list image'
        run: make ps

      - name: 'Push to container registry'
        run: make push

